-- REF-02 — carga da biblioteca de legislações saneada.
--
-- GERADO por scripts/ref02-build-migration.ts a partir de
-- src/data/legislationLibrary.ts. Não editar à mão: altere a biblioteca e
-- regenere, senão o código e o banco divergem de novo.
--
-- O que faz:
--   * atualiza as 41 linhas que já existem (nome canônico, ementa, URL, uf, segmentos),
--     casadas por chave canônica — não por nome, porque grafias como
--     "Decreto Nº 57501 DE 30/01/2026" e "Decreto Rio nº 57.501/2026" são o
--     mesmo ato e um upsert por nome criaria duplicata;
--   * insere as 37 entradas novas, de forma idempotente (insert ... where not exists).
--
-- O que NÃO faz, de propósito:
--   * não apaga nenhuma linha. A biblioteca é editável pela LegislationsManager;
--     linha criada pela Ester não pode sumir numa migration. As linhas do banco
--     sem correspondência na biblioteca ficam como estão:
--       OUTRO|| — Constituição da República Federativa do Brasil
--   * não mexe em checklist_items. O backfill de legislation_url é o
--     scripts/ref02-backfill-item-urls.mjs, que reusa a mesma resolução do app.
--
--   * não sobrescreve ementa mais rica. Várias foram ampliadas à mão pela Ester
--     na LegislationsManager (a da Lei 8.842/1994 explica a vedação de permanência
--     de quem precisa de assistência permanente). A biblioteca só substitui a
--     ementa quando o banco tem menos texto do que ela.
--
-- Reexecutável: o update é por id e o insert é condicionado a "not exists".

-- ── Linhas existentes: nome canônico, URL oficial, UF e segmentos ───────────
update public.legislations l set
  name     = b.name,
  summary  = case when length(coalesce(l.summary, '')) > length(b.summary) then l.summary else b.summary end,
  url      = b.url,
  uf       = b.uf,
  segments = b.segments
from (values
  ('9ce086e8-fce0-4383-a179-bc677b3cdfcf'::uuid, 'RDC Anvisa nº 63/2011', 'Dispõe sobre os Requisitos de Boas Práticas de Funcionamento para os Serviços de Saúde.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2011/res0063_25_11_2011.html', null, array['saude', 'estetica']::text[]),
  ('88f74734-dac2-4f9a-bfa9-20c05ceee1f4'::uuid, 'RDC Anvisa nº 50/2002', 'Regulamento técnico para planejamento, programação, elaboração e avaliação de projetos físicos de estabelecimentos assistenciais de saúde.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2002/res0050_21_02_2002.html', null, array['saude', 'estetica']::text[]),
  ('c8b239ac-f650-43c9-9989-cfcdefb7ac2e'::uuid, 'RDC Anvisa nº 15/2012', 'Requisitos de boas práticas para o processamento de produtos para saúde.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2012/rdc0015_15_03_2012.html', null, array['saude', 'estetica']::text[]),
  ('0c6871f2-2e0f-4273-8d59-4f999fa38013'::uuid, 'RDC Anvisa nº 36/2013', 'Institui ações para a segurança do paciente em serviços de saúde.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2013/rdc0036_25_07_2013.html', null, array['saude', 'estetica']::text[]),
  ('06ecbc90-58a5-4d29-8209-f41a1fa266ea'::uuid, 'RDC Anvisa nº 222/2018', 'Regulamenta as Boas Práticas de Gerenciamento dos Resíduos de Serviços de Saúde (PGRSS). Substitui a RDC 306/2004, revogada.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2018/rdc0222_28_03_2018.pdf', null, array['ilpi', 'saude', 'estetica']::text[]),
  ('826e9660-e6ec-484b-a2c7-f94ae9360560'::uuid, 'RDC Anvisa nº 751/2022', 'Requisitos sanitários aplicáveis aos serviços de saúde que utilizam equipamentos emissores de radiações ionizantes para diagnóstico.', 'https://www.in.gov.br/en/web/dou/-/resolucao-rdc-n-751-de-21-de-setembro-de-2022-430929547', null, array['saude', 'estetica']::text[]),
  ('39fe1c06-6d02-44fd-b282-d434b9ff3c57'::uuid, 'RDC Nº 7/2010', 'Requisitos mínimos para o funcionamento de Unidades de Terapia Intensiva.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2010/res0007_24_02_2010.html', null, array['saude']::text[]),
  ('9b5af7b2-4f53-45d9-9b57-092cef99069a'::uuid, 'RDC Anvisa nº 502/2021', 'Dispõe sobre o funcionamento de Instituição de Longa Permanência para Idosos (ILPI). Revogou as RDC 283/2005 e 94/2007.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2020/rdc0502_27_05_2021.pdf', null, array['ilpi']::text[]),
  ('ecec061a-bc56-434c-8b05-9706bbd5258c'::uuid, 'RDC Anvisa nº 216/2004', 'Regulamento Técnico de Boas Práticas para Serviços de Alimentação. Aplica-se a qualquer serviço de alimentação, sem exceção por porte.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2004/res0216_15_09_2004.html', null, array['alimentos']::text[]),
  ('7fffb46e-0ebe-4f9b-b5db-a0d38f1abcd8'::uuid, 'Lei Federal nº 6.437/1977', 'Configura infrações à legislação sanitária federal e estabelece as sanções respectivas.', 'https://www.planalto.gov.br/ccivil_03/leis/l6437.htm', null, null),
  ('00fd31f3-dc5c-4729-a3cd-20609b7df60b'::uuid, 'Lei Federal nº 8.078/1990', 'Código de Defesa do Consumidor; base do dever de informação e do termo de consentimento na relação com o cliente.', 'https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm', null, array['saude', 'estetica', 'ilpi']::text[]),
  ('3c30f258-260a-4fde-b649-b22b883a19a7'::uuid, 'Lei Federal nº 8.080/1990', 'Lei Orgânica da Saúde; organiza o SUS e as ações de promoção, proteção e recuperação da saúde.', 'https://www.planalto.gov.br/ccivil_03/leis/l8080.htm', null, null),
  ('e22cce96-a538-4883-a039-ce781525d305'::uuid, 'Lei Federal nº 8.842/1994', 'Institui a Política Nacional do Idoso e orienta ações de autonomia, integração e participação social.', 'https://www.planalto.gov.br/ccivil_03/leis/l8842.htm', null, array['ilpi']::text[]),
  ('1789b058-ee5d-45fc-ade8-11c35f860119'::uuid, 'Lei Federal nº 10.741/2003', 'Estatuto da Pessoa Idosa; direitos da pessoa idosa e deveres das instituições de atendimento.', 'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741compilado.htm', null, array['ilpi']::text[]),
  ('73ebc7a1-e317-434c-904f-c95a9ff864ee'::uuid, 'Lei Federal nº 14.423/2022', 'Atualiza a nomenclatura legal de "idoso" para "pessoa idosa" no Estatuto da Pessoa Idosa.', 'https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2022/Lei/L14423.htm', null, array['ilpi']::text[]),
  ('c85daa03-c1cf-485b-9659-92f20e41e052'::uuid, 'Lei Federal nº 14.602/2023', 'Altera a Lei do Exercício da Enfermagem para garantir local de descanso à equipe de enfermagem.', 'https://www.planalto.gov.br/ccivil_03/_Ato2023-2026/2023/Lei/L14602.htm', null, array['ilpi', 'saude']::text[]),
  ('4a4cd390-a864-48e5-bc71-8870566371c3'::uuid, 'Portaria SVS/MS nº 344/1998', 'Regulamento Técnico sobre substâncias e medicamentos sujeitos a controle especial.', 'https://bvsms.saude.gov.br/bvs/saudelegis/svs/1998/prt0344_12_05_1998_rep.html', null, array['saude', 'estetica', 'ilpi']::text[]),
  ('d8e41207-0873-4213-a0b0-f3f2ff8962f2'::uuid, 'NR-32', 'Segurança e Saúde no Trabalho em Serviços de Saúde; risco biológico, vacinação ocupacional e perfurocortantes.', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-32', null, array['saude', 'estetica', 'ilpi']::text[]),
  ('6d3f480f-35b8-49e5-b06b-98278daecba3'::uuid, 'ABNT NBR 9050', 'Acessibilidade a edificações, mobiliário, espaços e equipamentos urbanos. Versão vigente: NBR 9050:2020, versão corrigida de 25/01/2021.', 'https://www.abntcatalogo.com.br/pnm.aspx?Q=czJRSjkwNTA=', null, array['ilpi', 'saude', 'estetica']::text[]),
  ('6ae8b52a-a87b-402c-a6eb-1d1de15e61d9'::uuid, 'Decreto Rio nº 57.501/2026', 'Código Sanitário do município do Rio de Janeiro.', 'https://vigilanciasanitaria.prefeitura.rio/wp-content/uploads/sites/84/2026/04/Decreto-N%C2%B0-57501_2026.pdf', 'RJ', null),
  ('0184e2c4-b66e-4614-b75d-65f0b14e3ba8'::uuid, 'Decreto Municipal 1.601/1992 (RJ Capital)', 'Aprova o Regulamento de Alimentos do Município do Rio de Janeiro.', 'http://www.rio.rj.gov.br/dlstatic/storage/proprio/arquivo/8/9/8/3134/Decreto1601.pdf', 'RJ', array['alimentos']::text[]),
  ('92d27e75-244c-4e71-be35-4a965bdddc30'::uuid, 'Lei Municipal RJ nº 8.618/2024', 'Obriga sala ou local de descanso para a equipe de enfermagem em estabelecimentos de saúde do município do Rio de Janeiro.', 'https://www.cofen.gov.br/prefeitura-do-rio-de-janeiro-sanciona-lei-de-descanso-digno-para-a-categoria/', 'RJ', array['ilpi', 'saude']::text[]),
  ('fa9ebc85-4b9a-46ea-a58d-b2b039098083'::uuid, 'Lei Ordinária RJ nº 8.049/2018', 'Estabelece normas para o funcionamento das ILPI no âmbito do Estado do Rio de Janeiro.', 'https://leisestaduais.com.br/rj/lei-ordinaria-n-8049-2018-rio-de-janeiro-estabelece-normas-para-o-funcionamento-das-instituicoes-de-longa-permanencia-de-idosos-ilpis-no-ambito-do-estado-do-rio-de-janeiro', 'RJ', array['ilpi']::text[]),
  ('36d32187-10a3-4531-90f5-5d11a1773c0e'::uuid, 'Resolução SES/RJ nº 1.568/2017', 'Critérios e procedimentos para o licenciamento sanitário no Estado do Rio de Janeiro.', 'https://www.saude.rj.gov.br/legislacao', 'RJ', null),
  ('40d6dc14-1707-444d-8a62-c34f40a20d91'::uuid, 'Portaria CVS 5/2013', 'Boas práticas para estabelecimentos comerciais de alimentos e serviços de alimentação no Estado de São Paulo.', 'https://www.cvs.saude.sp.gov.br/zip/A_Portaria%20CVS%205_2013.pdf', 'SP', array['alimentos']::text[]),
  ('f3f7a46b-7feb-435d-8231-39213eefc754'::uuid, 'Portaria 2619/2011 (SP Capital)', 'Regulamento Técnico de Boas Práticas para alimentos no município de São Paulo.', 'https://www.prefeitura.sp.gov.br/cidade/secretarias/upload/chamadas/portaria_2619_2011_1323348123.pdf', 'SP', array['alimentos']::text[]),
  ('2b1ab37f-6dd1-4ce9-84b7-2ed8817538e7'::uuid, 'Resolução SES/MG nº 7.426/2021', 'Regras estaduais de licenciamento sanitário e prazos de liberação em Minas Gerais.', 'https://www.saude.mg.gov.br/wp-content/uploads/2020/11/2.-Resolucao-n-7426_2021%E2%80%AF-1de.pdf', 'MG', null),
  ('3ceeefc4-e5da-4a4f-bec2-f037bcaa0a87'::uuid, 'Lei Municipal nº 7.031/1996 - Belo Horizonte', 'Institui o Código Sanitário Municipal de Belo Horizonte.', 'https://leismunicipais.com.br/a/mg/b/belo-horizonte/lei-ordinaria/1996/704/7031/lei-ordinaria-n-7031-1996-dispoe-sobre-a-normatizacao-complementar-dos-procedimentos-relativos-a-saude-pelo-codigo-sanitario-municipal-e-da-outras-providencias', 'MG', null),
  ('5fa8df23-8b58-4800-ab47-516ebfbf4002'::uuid, 'Lei Municipal nº 7.930/1999 - Belo Horizonte', 'Institui a Política Municipal do Idoso em Belo Horizonte.', 'https://leismunicipais.com.br/a/mg/b/belo-horizonte/lei-ordinaria/1999/793/7930/lei-ordinaria-n-7930-1999-institui-a-politica-municipal-do-idoso', 'MG', array['ilpi']::text[]),
  ('f44ec428-2308-4457-91a3-c74b1c3a5721'::uuid, 'Decreto Municipal nº 17.944/2022 - Belo Horizonte', 'Regulamenta os procedimentos para concessão do Alvará de Autorização Sanitária em Belo Horizonte.', 'https://www.legisweb.com.br/legislacao/?legislacao=430959', 'MG', null),
  ('f8a1e953-a9e1-4d48-9641-6f76aec941ee'::uuid, 'Portaria SMS nº 12/2015 - Belo Horizonte', 'Padrão mínimo de funcionamento das ILPI no município de Belo Horizonte.', 'https://www.legisweb.com.br/legislacao/?id=283029', 'MG', array['ilpi']::text[]),
  ('34ae3cbb-7d60-4b5d-b561-5ad71987d77d'::uuid, 'Portaria SMSA/SUS-BH nº 0221/2022', 'Procedimentos do licenciamento sanitário e classificação de risco em Belo Horizonte.', 'https://visabh.webnode.page/portarias-visa-bh-/', 'MG', null),
  ('84e2a4ed-1b45-4121-8dfa-e12dc728c206'::uuid, 'Resolução CNDI nº 33/2017', 'Diretrizes para o contrato de prestação de serviços entre ILPI ou casa-lar e pessoa idosa.', 'https://www.gov.br/participamaisbrasil/resolucao-n-33-de-24-de-maio-de-2017', null, array['ilpi']::text[]),
  ('b1692068-5748-4ae5-af0b-597ff880e863'::uuid, 'CBO 5162-10 - Cuidador de Idosos', 'Descrição da ocupação de cuidador de idosos na Classificação Brasileira de Ocupações.', 'https://cbo.mte.gov.br/cbosite/pages/pesquisas/BuscaPorTitulo.jsf', null, array['ilpi']::text[]),
  ('a2d2e21f-e1cc-41a3-bb59-42a26ee4836d'::uuid, 'Resolução COFEN nº 450/2013', 'Normatiza o procedimento de sondagem vesical no âmbito da equipe de enfermagem.', 'https://www.cofen.gov.br/resolucao-cofen-no-04502013-4/', null, array['ilpi']::text[]),
  ('a814841c-be14-44f1-b8eb-f970fd19d72c'::uuid, 'Resolução COFEN nº 557/2017', 'Normatiza a atuação da enfermagem no procedimento de aspiração de vias aéreas.', 'https://www.cofen.gov.br/resolucao-cofen-no-05572017/', null, array['ilpi']::text[]),
  ('cba03998-630b-476c-87ac-f317e310ba9f'::uuid, 'Resolução COFEN nº 619/2019', 'Normatiza a atuação da enfermagem em sondagem oro/nasogástrica e nasoentérica.', 'https://www.cofen.gov.br/resolucao-cofen-no-619-2019/', null, array['ilpi']::text[]),
  ('e58a2001-b794-4c20-bcea-84e8fce9d87b'::uuid, 'Resolução COFEN nº 725/2023', 'Normas e diretrizes para o sistema de fiscalização dos Conselhos de Enfermagem.', 'https://www.cofen.gov.br/resolucao-cofen-no-725-de-15-de-setembro-de-2023/', null, array['ilpi']::text[]),
  ('002394ff-0fd3-4483-85e4-c22cbc5ecf12'::uuid, 'Resolução COFEN nº 746/2024', 'Normatiza a contenção mecânica de pacientes, sob supervisão direta do enfermeiro.', 'https://www.cofen.gov.br/resolucao-cofen-no-746-de-20-de-marco-de-2024/', null, array['ilpi']::text[]),
  ('7bbe8549-dc6e-4a72-92fc-83f4249c397e'::uuid, 'Resolução COFEN nº 787/2025', 'Regulamenta a atuação da enfermagem no cuidado a pessoas com lesões cutâneas.', 'https://www.cofen.gov.br/resolucao-cofen-no-787-de-21-de-agosto-de-2025/', null, array['ilpi']::text[]),
  ('920d4eaa-d278-40ba-8bde-1bc4b018d91a'::uuid, 'Parecer COFEN nº 022/2022', 'Trata da capacitação de cuidador leigo pelo enfermeiro em assistência específica no domicílio.', 'https://www.cofen.gov.br/parecer-de-camara-tecnica-no-0081-2021-ctln-cofen/', null, array['ilpi']::text[])
) as b(id, name, summary, url, uf, segments)
where l.id = b.id;

-- ── Atos citados pelos roteiros que ainda não estavam na biblioteca ─────────
insert into public.legislations (name, summary, url, uf, segments)
select b.name, b.summary, b.url, b.uf, b.segments
from (values
  ('RDC Anvisa nº 51/2011', 'Requisitos mínimos para análise, avaliação e aprovação dos projetos físicos de estabelecimentos de saúde (Projeto Básico de Arquitetura).', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2011/rdc0051_06_10_2011.html', null, array['saude', 'estetica']::text[]),
  ('RDC Anvisa nº 42/2010', 'Obrigatoriedade de disponibilização de preparação alcoólica para fricção antisséptica das mãos pelos serviços de saúde.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2010/res0042_25_10_2010.html', null, array['saude', 'estetica']::text[]),
  ('RDC Anvisa nº 156/2006', 'Dispõe sobre o registro, rotulagem e reprocessamento de produtos médicos; obriga a rotulagem "proibido reprocessar" quando aplicável.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2006/res0156_11_08_2006.html', null, array['saude', 'estetica']::text[]),
  ('RE Anvisa nº 2.605/2006', 'Estabelece a lista de produtos médicos enquadrados como de uso único cujo reprocessamento é proibido.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2006/res2605_11_08_2006.html', null, array['saude', 'estetica']::text[]),
  ('RDC Anvisa nº 56/2009', 'Proíbe em todo o território nacional o uso de equipamento de bronzeamento artificial com emissão de radiação ultravioleta para fins estéticos.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2009/rdc0056_09_11_2009.html', null, array['estetica']::text[]),
  ('RDC Anvisa nº 67/2007', 'Boas Práticas de Manipulação de preparações magistrais e oficinais para uso humano em farmácias. É a norma de origem do produto manipulado que a clínica utiliza.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2007/rdc0067_08_10_2007.html', null, array['saude', 'estetica']::text[]),
  ('RDC Anvisa nº 509/2021', 'Dispõe sobre o gerenciamento de tecnologias em saúde em estabelecimentos de saúde, do recebimento ao descarte do equipamento.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2020/rdc0509_27_05_2021.pdf', null, array['saude', 'estetica']::text[]),
  ('Nota Técnica Anvisa nº 2/2024', 'Esclarece a aplicação das normas sanitárias aos serviços de estética e delimita a fronteira entre embelezamento e serviço de saúde. Substitui a NT 15/2023.', 'https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/servicosdesaude/notas-tecnicas/notas-tecnicas-vigentes/nota-tecnica-no-2-2024-sei-ggtes-dire3-anvisa-esclarecimentos-sobre-os-servicos-de-estetica-e-atendimento-as-normas-sanitarias-aplicaveis-a-esses-servicos', null, array['estetica']::text[]),
  ('RDC Anvisa nº 503/2021', 'Fixa os requisitos mínimos exigidos para a Terapia de Nutrição Enteral (TNE).', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2020/rdc0503_27_05_2021.pdf', null, array['ilpi', 'saude']::text[]),
  ('RDC Anvisa nº 430/2020', 'Boas Práticas de Distribuição, Armazenagem e de Transporte de Medicamentos, incluindo controle de temperatura de termolábeis. Alterada pela RDC 653/2022.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2020/rdc0430_08_10_2020.pdf', null, array['ilpi', 'saude']::text[]),
  ('RDC Anvisa nº 218/2005', 'Procedimentos higiênico-sanitários para manipulação de alimentos e bebidas preparados com vegetais.', 'https://bvsms.saude.gov.br/bvs/saudelegis/anvisa/2005/rdc0218_29_07_2005.html', null, array['alimentos']::text[]),
  ('Lei Federal nº 6.360/1976', 'Vigilância sanitária a que ficam sujeitos os medicamentos, cosméticos, saneantes e produtos correlatos; exige regularização junto à Anvisa.', 'https://www.planalto.gov.br/ccivil_03/leis/l6360.htm', null, array['saude', 'estetica']::text[]),
  ('Lei Federal nº 8.742/1993', 'Lei Orgânica da Assistência Social (LOAS); organiza a assistência social e disciplina o registro das entidades no CNAS.', 'https://www.planalto.gov.br/ccivil_03/leis/l8742compilado.htm', null, array['ilpi']::text[]),
  ('Lei Federal nº 9.294/1996', 'Restringe o uso de produtos fumígenos; com a redação da Lei 12.546/2011, proíbe fumar em recinto coletivo fechado.', 'https://www.planalto.gov.br/ccivil_03/leis/l9294.htm', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('Lei Federal nº 13.589/2018', 'Obriga edifícios de uso público e coletivo com climatização artificial a manter Plano de Manutenção, Operação e Controle (PMOC).', 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13589.htm', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('Lei Federal nº 13.709/2018', 'Lei Geral de Proteção de Dados Pessoais (LGPD); disciplina o tratamento de dados de saúde e o acesso ao prontuário.', 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm', null, array['saude', 'estetica', 'ilpi']::text[]),
  ('Decreto Federal nº 9.013/2017', 'RIISPOA — Regulamento da Inspeção Industrial e Sanitária de Produtos de Origem Animal; base do registro SIF/SIE/SIM. Alterado pelo Decreto 10.468/2020, não revogado.', 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/decreto/d9013.htm', null, array['alimentos']::text[]),
  ('Portaria de Consolidação GM/MS nº 4/2017', 'Consolida as normas sobre os sistemas e subsistemas do SUS; o Anexo V traz a Lista Nacional de Notificação Compulsória, atualizada em 2026.', 'https://bvsms.saude.gov.br/bvs/saudelegis/gm/2017/prc0004_03_10_2017.html', null, array['saude', 'estetica', 'ilpi']::text[]),
  ('Portaria GM/MS nº 888/2021', 'Padrão de potabilidade e procedimentos de controle e vigilância da qualidade da água para consumo humano (Anexo XX da PRC 5/2017).', 'https://bvsms.saude.gov.br/bvs/saudelegis/gm/2021/prt0888_07_05_2021.html', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('NR-1', 'Disposições gerais de Segurança e Saúde no Trabalho e gerenciamento de riscos ocupacionais (PGR).', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('NR-6', 'Equipamento de Proteção Individual (EPI); obriga o fornecimento gratuito e o registro de entrega, com CA válido.', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-6', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('NR-7', 'Programa de Controle Médico de Saúde Ocupacional (PCMSO); exames admissional, periódico e demissional.', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-7', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('NR-10', 'Segurança em instalações e serviços em eletricidade; medidas de controle e sistemas preventivos.', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-10', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('NR-24', 'Condições sanitárias e de conforto nos locais de trabalho: sanitários, vestiário e guarda de pertences.', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-24', null, array['saude', 'estetica', 'ilpi', 'alimentos']::text[]),
  ('ABNT NBR 13534', 'Instalações elétricas de baixa tensão — requisitos específicos para estabelecimentos assistenciais de saúde. Versão vigente: 2008.', 'https://www.abntcatalogo.com.br/pnm.aspx?Q=czJRSjEzNTM0', null, array['saude', 'estetica']::text[]),
  ('Portaria IVISA-RIO nº 002/2020', 'Regulamento técnico de Boas Práticas para estabelecimentos de alimentos no município do Rio de Janeiro; complementa a RDC 216/2004.', 'https://vigilanciasanitaria.prefeitura.rio/licenciamento-sanitario/licenciamento-sanitario-legislacao/', 'RJ', array['alimentos']::text[]),
  ('Decreto Rio nº 45.585/2018', 'Regulamento administrativo do Código de Vigilância Sanitária do município do Rio de Janeiro: licenciamento sanitário e procedimentos fiscalizatórios.', 'http://www.rio.rj.gov.br/dlstatic/10112/10308893/4263216/DecretoRio455852018CONSOLIDADO06122019.pdf', 'RJ', array['alimentos', 'saude', 'estetica', 'ilpi']::text[]),
  ('Resolução SES/RJ nº 1.822/2019', 'Aprova a relação de documentos para regularização de estabelecimentos sujeitos à vigilância sanitária no Estado do Rio de Janeiro. Revogou a Resolução SES 1.480/2016.', 'https://sistemas.saude.rj.gov.br/protocoloonline/Documentos/Resolucoes/Res_1822.html', 'RJ', null),
  ('Resolução CREMERJ nº 192/2021', 'Disciplina a direção técnica e a responsabilidade técnica médica nos estabelecimentos de saúde do Estado do Rio de Janeiro.', 'https://www.cremerj.org.br/resolucoes/', 'RJ', array['saude', 'ilpi']::text[]),
  ('Lei Estadual nº 16.140/2007 - Goiás', 'Dispõe sobre o SUS no Estado de Goiás e sobre a organização, fiscalização e controle das ações e serviços de saúde nas esferas estadual e municipal.', 'https://legisla.casacivil.go.gov.br/pesquisa_legislacao/86552/lei-16140', 'GO', array['ilpi', 'saude', 'estetica', 'alimentos']::text[]),
  ('Lei Municipal nº 1.812/2014 - Senador Canedo', 'Institui o Código Sanitário do Município de Senador Canedo (GO); base municipal do licenciamento e da fiscalização sanitária local.', 'https://leismunicipais.com.br/a/go/s/senador-canedo/lei-ordinaria/2014/182/1812/lei-ordinaria-n-1812-2014-institui-o-codigo-sanitario-do-municipio-de-senador-canedo-e-da-outras-providencias', 'GO', array['ilpi', 'saude', 'estetica', 'alimentos']::text[]),
  ('Resolução CNAS nº 109/2009', 'Aprova a Tipificação Nacional dos Serviços Socioassistenciais; enquadra o acolhimento institucional de pessoa idosa na proteção social especial de alta complexidade.', 'https://www.mds.gov.br/webarquivos/public/resolucao_cnas_n109_%202009.pdf', null, array['ilpi']::text[]),
  ('Decreto Federal nº 94.406/1987', 'Regulamenta a Lei 7.498/1986 (exercício da enfermagem) e delimita as atribuições de enfermeiro, técnico e auxiliar.', 'https://www.planalto.gov.br/ccivil_03/decreto/1980-1989/d94406.htm', null, array['ilpi', 'saude']::text[]),
  ('Lei Complementar nº 123/2006', 'Estatuto Nacional da Microempresa e da Empresa de Pequeno Porte; base do tratamento diferenciado em obrigações acessórias.', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp123.htm', null, null),
  ('Resolução COFEN nº 582/2018', 'Veda a participação do enfermeiro no ensino de práticas privativas de enfermagem em capacitação de cuidador de idosos.', 'https://www.cofen.gov.br/resolucao-cofen-no-582-2018_64391.html', null, array['ilpi']::text[]),
  ('Resolução COFEN nº 620/2019', 'Normatiza as atribuições dos profissionais de enfermagem em Instituição de Longa Permanência para Idosos.', 'https://www.cofen.gov.br/resolucao-cofen-no-620-2019/', null, array['ilpi']::text[]),
  ('Resolução COFEN nº 736/2024', 'Dispõe sobre a implementação do Processo de Enfermagem. REVOGOU a Resolução COFEN 358/2009 e eliminou o termo "SAE".', 'https://www.cofen.gov.br/resolucao-cofen-no-736-de-17-de-janeiro-de-2024/', null, array['ilpi', 'saude']::text[])
) as b(name, summary, url, uf, segments)
where not exists (select 1 from public.legislations l where l.name = b.name);
